

 AWS_ACCESS_KEY: "AKIAJLFPAPAUY2SWJUHQ"
 AWS_SECRET_KEY: "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"
 AWS_BUCKET: "amsonline"
 SENDGRID_USERNAME: app76390799@heroku.com
 SENDGRID_PASSWORD: bprhisn33912 
